global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flow-pages-backend'
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Temporarily enabling to test certificate issues
    static_configs:
      - targets: ['flow-pages-backend-production.up.railway.app']
